name: Push to JFrog

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:   # 👈 Here we load the environment variables
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_DOCKER_REPO: ${{ secrets.JFROG_DOCKER_REPO }}
      JFROG_GENERIC_REPO: ${{ secrets.JFROG_GENERIC_REPO }}
      JFROG_USER: ${{ secrets.JFROG_USER }}
      JFROG_PASSWORD: ${{ secrets.JFROG_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to JFrog Docker
        run: |
          echo "${JFROG_PASSWORD}" | docker login ${JFROG_URL} \
            --username "${JFROG_USER}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t ${JFROG_URL}/${JFROG_DOCKER_REPO}/myapp:1.0 .
          docker push ${JFROG_URL}/${JFROG_DOCKER_REPO}/myapp:1.0

      - name: Upload Generic Artifact
        run: |
          curl -u "${JFROG_USER}:${JFROG_PASSWORD}" \
            -T target/myapp-1.0.tar.gz \
            "${JFROG_URL}/artifactory/${JFROG_GENERIC_REPO}/myapp-1.0.tar.gz"
