name: Go Build & Push to JFrog

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Go binary
      run: |
        go mod tidy
        go build -o myapp hello.go

    - name: Build Docker image
      run: |
        IMAGE_NAME="myapp"
        IMAGE_TAG="1.0"
        docker build -t ${{ secrets.JFROG_REGISTRY }}/docker/$IMAGE_NAME:$IMAGE_TAG .

    - name: Log in to JFrog Docker registry
      run: |
        echo "${{ secrets.JFROG_IDENTITY_TOKEN }}" | docker login ${{ secrets.JFROG_REGISTRY }} \
          --username "accesstoken" --password-stdin

    - name: Push Docker image to JFrog
      run: |
        IMAGE_NAME="myapp"
        IMAGE_TAG="1.0"
        docker push ${{ secrets.JFROG_REGISTRY }}/docker/$IMAGE_NAME:$IMAGE_TAG

    - name: Upload raw binary to JFrog Generic repo
      run: |
        curl -u "accesstoken:${{ secrets.JFROG_IDENTITY_TOKEN }}" \
        -T ./myapp \
        "${{ secrets.JFROG_URL }}/golang-artifacts-local/myapp"
