name: Golang CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Go binary
      run: |
        go mod tidy
        go build -o myapp hello.go

    - name: Log in to JFrog Docker registry
      run: |
        echo "${{ secrets.JFROG_API_KEY }}" | docker login ${{ secrets.JFROG_REGISTRY }} \
          --username "${{ secrets.JFROG_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        IMAGE_NAME="myapp"
        IMAGE_TAG="1.0"
        docker build -t ${{ secrets.JFROG_REGISTRY }}/${{ secrets.JFROG_DOCKER_REPO }}/$IMAGE_NAME:$IMAGE_TAG .

    - name: Push Docker image to JFrog
      run: |
        IMAGE_NAME="myapp"
        IMAGE_TAG="1.0"
        docker push ${{ secrets.JFROG_REGISTRY }}/${{ secrets.JFROG_DOCKER_REPO }}/$IMAGE_NAME:$IMAGE_TAG

    - name: Upload raw binary to JFrog Generic repo
      run: |
        curl -u "${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_API_KEY }}" \
          -T ./myapp \
          "${{ secrets.JFROG_URL }}/${{ secrets.JFROG_GENERIC_REPO }}/myapp"
